"""Decode as one CUDA graph per byte (decided 2026-08-24, docs/shape.md; FreeToken 2608.16157 showed the
pattern: every routing-dependent decision lives on the device as data inside a captured graph).

Per replay:  u ~ U[0,1)                                      (parent graph — RNG is refused inside a conditional body)
             IF ¬done:  sample the next byte from `logits` (temperature / nucleus, inverse CDF with u)
                        write it to the ring; done |= stop id
                        IF ¬done:  encoder step → router → IF boundary: main network over the arena,
                                   S += 1 → dechunk → decoder → lm_head → `logits`; n_out += 1;
                                   done |= n_out ≥ max_out

The router bit never reaches the host: the main step is a CUDA-graph IF node keyed on the device
tensor (`CUDAGraph.begin_capture_to_if_node`, torch 2.13). Sampling stays on the device too, so the host
only drains the rings every K replays (one sync per K bytes) and sees at most K-1 bytes of overshoot
after a stop — and no state overshoot at all, because `done` freezes the step exactly at the stop.

The Relation main step reads the arena at a static width (a bucket of rows ≥ S + K, masked past S), one
captured graph per bucket; every Mamba-3 / routing / dechunk tensor is written in place. Graph mode is
for models without a multi-byte head (the flagship); the 35M's speculative rounds stay eager.
"""

from __future__ import annotations

import math
import threading
import time
from typing import Callable, Dict, List, Optional, Tuple

import torch
import torch.nn.functional as F

from ..model.arena import ArenaLayer, RelationArena
from ..model.hnet import HNetForCausalLM, InferenceState
from ..model.mamba3 import Mamba3Mixer
from ..model.relation import FullRelation, _rotate_half

BUCKET = 256  # arena rows per captured width


def _if_node(pred: torch.Tensor):
    """Context manager: capture the body as a conditional node on `pred` (0-d bool CUDA tensor)."""
    g = torch.cuda.CUDAGraph.get_currently_capturing_graph()
    g.begin_capture_to_if_node(pred)

    class _Ctx:
        def __enter__(self):
            return self

        def __exit__(self, *a):
            g.end_capture_to_conditional_node()
            return False

    return _Ctx()


class GraphDecoder:
    K = 8  # replays per host sync

    def __init__(self, model: HNetForCausalLM, arena: RelationArena, device, stop_ids, ring_size: int, seed: int = 0, pool=None):
        assert model.mbp_head is None, "graph decode is for models without a multi-byte head"
        self.model, self.arena, self.device = model, arena, torch.device(device)
        self.pool = pool  # the engine's serving MemPool id: captures allocate there instead of a private pool
        cfg = model.cfg
        self.D0 = cfg.d_model_outer
        self.V = model.lm_head.weight.shape[0]
        self.dtype = model.lm_head.weight.dtype
        dev = self.device
        # the static working state (Mamba-3 / routing / dechunk tensors the graph reads and writes in place)
        self.state = model.allocate_inference_state(dev, arena=arena)
        # device-resident control and sampling parameters
        self.logits = torch.zeros(self.V, device=dev, dtype=torch.float32)
        self.u = torch.zeros((), device=dev)
        self.temp = torch.ones((), device=dev)
        self.top_p = torch.ones((), device=dev)
        self.greedy = torch.zeros((), device=dev, dtype=torch.bool)
        self.done = torch.zeros((), device=dev, dtype=torch.bool)
        self.n_out = torch.zeros((), device=dev, dtype=torch.long)
        self.max_out = torch.zeros((), device=dev, dtype=torch.long)
        self.S = torch.zeros((), device=dev, dtype=torch.long)
        self.wpos = torch.zeros((), device=dev, dtype=torch.long)
        self.byte = torch.zeros(1, 1, device=dev, dtype=torch.long)
        self.zc = torch.zeros(1, 1, self.D0, device=dev, dtype=self.dtype)
        self.is_stop = torch.zeros(self.V, device=dev, dtype=torch.bool)
        for i in stop_ids:
            if i < self.V:
                self.is_stop[i] = True
        self.one = torch.ones(1, device=dev, dtype=torch.long)
        # rings: one slot per generated byte
        R = int(ring_size)
        self.ring_bytes = torch.zeros(R, device=dev, dtype=torch.long)
        self.ring_p = torch.zeros(R, device=dev)
        self.ring_ent = torch.zeros(R, device=dev)
        self.ring_bp = torch.zeros(R, device=dev)
        self.ring_bit = torch.zeros(R, device=dev, dtype=torch.bool)
        self.mixers: List[Mamba3Mixer] = [b.mixer for b in list(model.encoder.layers) + list(model.decoder.layers)]
        nh = self.mixers[0].nheads if self.mixers else 1
        self.ring_ret = torch.zeros(R, len(self.mixers), nh, device=dev)
        self.ring_xm = torch.zeros(R, cfg.main.n_layers, device=dev)
        self.ret_dev = [{"retention": torch.zeros(nh, device=dev), "trapezoid": torch.zeros(nh, device=dev)} for _ in self.mixers]
        self.xm_dev = torch.zeros(cfg.main.n_layers, device=dev)
        # host mirrors (pinned) for the drain
        pin = dev.type == "cuda"
        self.h_meta = torch.zeros(4, dtype=torch.long, pin_memory=pin)  # wpos, done, n_out, S
        self.d_meta = torch.zeros(4, dtype=torch.long, device=dev)
        self.h_bytes = torch.zeros(R, dtype=torch.long, pin_memory=pin)
        self.h_f = torch.zeros(3, R, pin_memory=pin)  # p, entropy, boundary_p
        self.h_bit = torch.zeros(R, dtype=torch.bool, pin_memory=pin)
        self.h_ret = torch.zeros(R, len(self.mixers), nh, pin_memory=pin)
        self.h_xm = torch.zeros(R, cfg.main.n_layers, pin_memory=pin)
        self.gen = torch.Generator(device=dev)
        self.gen.manual_seed(seed)
        self.graphs: Dict[Tuple[int, int], torch.cuda.CUDAGraph] = {}
        self.kj = torch.arange(arena.capacity, device=dev)
        self._warm = False

    # ------------------------------------------------------------------------------
    def _mamba_stack_step(self, stack, hidden: torch.Tensor, states) -> torch.Tensor:
        residual = None
        for layer, st in zip(stack.layers, states):
            hidden, residual, new = layer.step(hidden, residual, st)
            st.angle.copy_(new.angle)
            st.ssm.copy_(new.ssm)
            st.k.copy_(new.k)
            st.v.copy_(new.v)
        return stack.rmsnorm(hidden, residual=residual, prenorm=False, residual_in_fp32=True)

    def _relation_step(self, mixer: FullRelation, x: torch.Tensor, al: ArenaLayer, Cb: int, li: int) -> torch.Tensor:
        """FullRelation.forward for one new chunk at device position S, reading arena rows [0, Cb)."""
        H, dh = mixer.n_heads, mixer.d_head
        D = mixer.d_model
        p1 = mixer.w1(x).view(1, 1, H, dh).transpose(1, 2)
        p2 = mixer.w2(x).view(1, 1, H, dh).transpose(1, 2)
        info = mixer.wi(x).view(1, 1, H, dh).transpose(1, 2)
        inv_freq = 1.0 / (mixer.rope_theta ** (torch.arange(0, dh, 2, device=x.device, dtype=torch.float32) / dh))
        freqs = self.S.float() * inv_freq
        emb = torch.cat([freqs, freqs], dim=-1)
        cos, sin = emb.cos().to(x.dtype)[None, None, None], emb.sin().to(x.dtype)[None, None, None]
        p1 = p1 * cos + _rotate_half(p1) * sin
        p2 = p2 * cos + _rotate_half(p2) * sin
        info = mixer._givens(info)
        p2buf, infobuf = self.arena.p2(li), self.arena.info(li)
        idx = self.S.view(1)
        p2buf.index_copy_(2, idx, p2)
        infobuf.index_copy_(2, idx, info)
        p2_all, info_all = p2buf[:, :, :Cb], infobuf[:, :, :Cb]
        u = torch.matmul(p1, p2_all.transpose(-1, -2)).float() / math.sqrt(dh)  # [1,H,1,Cb]
        kj = self.kj[:Cb]
        is_self = kj == self.S
        is_past = kj < self.S
        log_i = torch.log((self.S + 1).float())
        r = torch.where(is_self, torch.sigmoid(u / mixer.tau_s), F.silu(u) - mixer.lam.float() * log_i)
        r = r.masked_fill(~(is_self | is_past), float("-inf"))
        flow = torch.softmax(r, dim=-1)
        y = torch.matmul(flow.to(info_all.dtype), info_all)  # [1,H,1,dh]
        self.xm_dev[li].copy_((1.0 - flow.gather(-1, idx.view(1, 1, 1, 1).expand(1, H, 1, 1)).squeeze(-1)).mean())
        return mixer.wo(y.transpose(1, 2).reshape(1, 1, D))

    def _main_step(self, hc: torch.Tensor, Cb: int) -> None:
        """Main network over the boundary row `hc` [1,1,D0] → self.zc; S += 1."""
        m = self.model
        hidden = m._pad(hc)
        residual = None
        for li, (block, al) in enumerate(zip(m.main_network.layers, self.state.main)):
            hidden, residual = block.norm1(hidden, residual=residual, prenorm=True, residual_in_fp32=block.residual_in_fp32)
            hidden = self._relation_step(block.mixer, hidden, al, Cb, li)
            if block.mlp is not None:
                hidden, residual = block.norm2(hidden, residual=residual, prenorm=True, residual_in_fp32=block.residual_in_fp32)
                hidden = block.mlp(hidden)
        zc = m.main_network.rmsnorm(hidden, residual=residual, prenorm=False, residual_in_fp32=True)
        self.zc.copy_(zc[..., : self.D0])
        self.ring_xm.index_copy_(0, self.wpos.view(1), self.xm_dev.view(1, -1))
        self.S.add_(1)

    def _consume(self, b: torch.Tensor, Cb: int, capturing: bool) -> None:
        """Feed byte `b` [1] through the model (in place) and write the next logits."""
        m, st = self.model, self.state
        self.byte.copy_(b.view(1, 1))
        h = m.embeddings(self.byte)
        h = self._mamba_stack_step(m.encoder, h, st.encoder)
        residual = m.residual_proj(h.float())
        routing = m.routing_module.step(h, st.routing)
        bit = routing.boundary_mask[0]
        prob = routing.boundary_prob[0, 1]
        slot = self.wpos.view(1)
        self.ring_bp.index_copy_(0, slot, prob.view(1))
        self.ring_bit.index_copy_(0, slot, bit.view(1))
        if capturing:
            with _if_node(bit):
                self._main_step(h, Cb)
        elif bool(bit):
            self._main_step(h, Cb)
        p = bit.float() * prob.clamp(min=m.dechunk_layer.eps, max=1 - m.dechunk_layer.eps)
        z = p * self.zc.float().squeeze(1) + (1 - p) * st.dechunk.last_value.float()
        st.dechunk.last_value.copy_(z.to(st.dechunk.last_value.dtype))
        h2 = (z[:, None, :] + residual).to(h.dtype)
        h3 = self._mamba_stack_step(m.decoder, h2, st.decoder)
        self.logits.copy_(m.lm_head(h3)[0, 0].float())
        if self.ret_dev:  # per-layer retention the mixers wrote into their device buffers this step
            self.ring_ret.index_copy_(0, slot, torch.stack([d["retention"] for d in self.ret_dev])[None])
        self.n_out.add_(1)
        self.wpos.add_(1)
        self.done.logical_or_(self.n_out >= self.max_out)

    def _sample(self) -> torch.Tensor:
        """Next byte from self.logits: [1] long. Writes p/entropy to the ring at wpos, sets done on a stop id."""
        lg = self.logits
        raw = torch.softmax(lg, 0)
        ent = -(raw * torch.log2(raw.clamp_min(1e-12))).sum()
        probs = torch.softmax(lg / self.temp, 0)
        ps, idx = torch.sort(probs, descending=True)
        cum = torch.cumsum(ps, 0)
        keep = (cum - ps) < self.top_p
        ps = torch.where(keep, ps, torch.zeros_like(ps))
        cum = torch.cumsum(ps, 0)
        j = torch.searchsorted(cum, (self.u * cum[-1]).reshape(1), right=True).clamp_(max=self.V - 1)
        b_sample = idx[j]
        b_greedy = lg.argmax().reshape(1)
        b = torch.where(self.greedy, b_greedy, b_sample)
        p_b = torch.where(self.greedy, raw[b_greedy], ps[j] / cum[-1])
        slot = self.wpos.view(1)
        self.ring_bytes.index_copy_(0, slot, b)
        self.ring_p.index_copy_(0, slot, p_b)
        self.ring_ent.index_copy_(0, slot, ent.view(1))
        self.done.logical_or_(self.is_stop[b][0])
        return b

    def _body(self, Cb: int, capturing: bool) -> None:
        self.u.copy_(torch.rand((), device=self.device, generator=self.gen))
        if capturing:
            with _if_node(torch.logical_not(self.done)):
                b = self._sample()
                with _if_node(torch.logical_not(self.done)):
                    self._consume(b, Cb, True)
        else:
            if not bool(self.done):
                b = self._sample()
                if not bool(self.done):
                    self._consume(b, Cb, False)

    # ------------------------------------------------------------------------------
    def _snapshot_static(self):
        st = self.state
        tensors = [t for s in st.encoder + st.decoder for t in s] + [st.routing.has_seen_tokens, st.routing.last_hidden_state, st.dechunk.last_value,
                                                                      self.logits, self.S, self.done, self.n_out, self.wpos, self.zc, self.max_out, self.u]
        return [t.clone() for t in tensors], tensors

    @torch.no_grad()
    def _warmup(self, Cb: int) -> None:
        """Run both branches eagerly once on a side stream so every kernel exists before capture."""
        saved, live = self._snapshot_static()
        s = torch.cuda.Stream()
        s.wait_stream(torch.cuda.current_stream())
        # Rows at or past S are scratch by contract, so the warm-up may write there; everything it
        # touches in the working state is restored below (the arena row it wrote stays scratch).
        self.arena.ensure(int(self.S) + 2)
        with torch.cuda.stream(s), torch.no_grad():
            self.done.fill_(False)
            self.max_out.fill_(1 << 30)
            self._body(Cb, capturing=False)  # whichever branch the router picks
            self._main_step(self.model.embeddings(self.byte), Cb)  # and the boundary path explicitly
            self.u.copy_(torch.rand((), device=self.device, generator=self.gen))
        torch.cuda.current_stream().wait_stream(s)
        torch.cuda.synchronize()
        for a, b in zip(saved, live):
            b.copy_(a)
        self._warm = True

    @torch.no_grad()
    def _graph(self, Cb: int) -> torch.cuda.CUDAGraph:
        key = (Cb, self.arena.generation)
        g = self.graphs.get(key)
        if g is None:
            # captures from an older arena generation point at freed memory: drop them
            self.graphs = {k: v for k, v in self.graphs.items() if k[1] == self.arena.generation}
            if self.kj.numel() != self.arena.capacity:
                self.kj = torch.arange(self.arena.capacity, device=self.device)
            if not self._warm:
                self._warmup(Cb)
            g = torch.cuda.CUDAGraph()
            g.register_generator_state(self.gen)
            with torch.cuda.graph(g, pool=self.pool):
                self._body(Cb, capturing=True)
            self.graphs[key] = g
        return g

    def invalidate(self) -> None:
        """Drop every capture (weights swapped into a rebuilt model, arena reallocated)."""
        self.close()
        self._warm = False

    def close(self) -> None:
        """Destroy the captured graphs deterministically (before the tensors they reference go away)."""
        if self.device.type == "cuda":
            torch.cuda.synchronize(self.device)
        for g in list(self.graphs.values()):
            g.reset()
        self.graphs.clear()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    # ------------------------------------------------------------------------------
    @torch.no_grad()
    def load(self, state: InferenceState, logits: torch.Tensor) -> None:
        """Copy a restored state into the static working state (the arena is shared already)."""
        st = self.state
        for dst, src in zip(st.encoder + st.decoder, state.encoder + state.decoder):
            dst.angle.copy_(src.angle); dst.ssm.copy_(src.ssm); dst.k.copy_(src.k); dst.v.copy_(src.v)
        st.routing.has_seen_tokens.copy_(state.routing.has_seen_tokens)
        st.routing.last_hidden_state.copy_(state.routing.last_hidden_state)
        st.dechunk.last_value.copy_(state.dechunk.last_value)
        st.main.n = state.main.n
        self.logits.copy_(logits.float())
        self.S.fill_(state.main.n)

    @torch.no_grad()
    def run(self, state: InferenceState, logits: torch.Tensor, temperature: float, top_p: float, max_out: int,
            stop: threading.Event, on_bytes: Callable[[List[dict]], None]) -> Tuple[str, InferenceState, torch.Tensor]:
        """Generate up to `max_out` bytes. `on_bytes` receives drained byte records
        {byte, p, entropy, boundary, boundary_p, retention[layer][head], exchange[layer], t_ms}.
        Returns (reason, the static state after the reply, next-byte logits)."""
        for m, d in zip(self.mixers, self.ret_dev):
            m.telemetry_dev = d
        try:
            self.load(state, logits)
            greedy = temperature <= 0
            self.greedy.fill_(greedy)
            self.temp.fill_(1.0 if greedy else float(temperature))
            self.top_p.fill_(float(top_p) if top_p < 1.0 else 1.0 + 1e-6)
            self.max_out.fill_(int(max_out))
            self.done.fill_(False)
            self.n_out.zero_()
            self.wpos.zero_()
            S_host = state.main.n
            drained = 0
            reason = "max_bytes"
            self.stop_id = None  # the stop id that ended the reply (the engine's tool hook reads it)
            K = self.K
            while True:
                if stop.is_set():
                    reason = "stopped"
                    break
                need = S_host + K + 1  # the query row must stay inside the captured width for K replays
                self.arena.ensure(need)  # a reallocation bumps the generation; _graph recaptures
                Cb = min(-(-need // BUCKET) * BUCKET, self.arena.capacity)
                g = self._graph(Cb)
                t0 = time.perf_counter()
                for _ in range(K):
                    g.replay()
                # one sync: control + the K new ring slots
                self.d_meta[0].copy_(self.wpos); self.d_meta[1].copy_(self.done); self.d_meta[2].copy_(self.n_out); self.d_meta[3].copy_(self.S)
                self.h_meta.copy_(self.d_meta, non_blocking=True)
                lo, hi = drained, drained + K + 1
                self.h_bytes[lo:hi].copy_(self.ring_bytes[lo:hi], non_blocking=True)
                self.h_f[0, lo:hi].copy_(self.ring_p[lo:hi], non_blocking=True)
                self.h_f[1, lo:hi].copy_(self.ring_ent[lo:hi], non_blocking=True)
                self.h_f[2, lo:hi].copy_(self.ring_bp[lo:hi], non_blocking=True)
                self.h_bit[lo:hi].copy_(self.ring_bit[lo:hi], non_blocking=True)
                self.h_ret[lo:hi].copy_(self.ring_ret[lo:hi], non_blocking=True)
                self.h_xm[lo:hi].copy_(self.ring_xm[lo:hi], non_blocking=True)
                torch.cuda.current_stream(self.device).synchronize()
                wpos, done, n_out, S_host = (int(x) for x in self.h_meta.tolist())
                dt = (time.perf_counter() - t0) * 1000 / max(wpos - drained, 1)
                recs = []
                for i in range(drained, wpos):
                    recs.append({"byte": int(self.h_bytes[i]), "p": float(self.h_f[0, i]), "entropy": float(self.h_f[1, i]),
                                 "boundary": bool(self.h_bit[i]), "boundary_p": float(self.h_f[2, i]),
                                 "retention": self.h_ret[i].tolist(), "exchange": self.h_xm[i].tolist() if bool(self.h_bit[i]) else None,
                                 "t_ms": dt})
                drained = wpos
                if recs:
                    on_bytes(recs)
                if done:
                    if n_out >= max_out:
                        reason = "max_bytes"
                    else:
                        reason = "eos"  # the stop id sits at ring[wpos], never consumed
                        self.stop_id = int(self.h_bytes[wpos])
                    break
            self.state.main.n = S_host
            return reason, self.state, self.logits.clone()
        finally:
            for m in self.mixers:
                m.telemetry_dev = None
